spring:
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml

  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/db-test
    driver-class-name: com.mysql.cj.jdbc.Driver
