spring:
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml
    drop-first: false
  logging:
    level: debug

  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/db-test
    driver-class-name: com.mysql.cj.jdbc.Driver


  # postgress配置
#  datasource:
#    username: postgres
#    password: 123456
#    url: jdbc:postgresql://127.0.0.1:5432/postgres
#    driver-class-name: org.postgresql.Driver
